name: Linux CI

on:
  push:
    branches:
      [ master, development ]
  pull_request:
      types: [opened, synchronize, reopened]

env:
  COMPATIBILITY_32_PATH: /usr/lib/i386-linux-gnu

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: prepare for 32 bit libraries
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y

    - name: install dependencies
      run: |
        sudo apt-get -y install \
          cmake gcc-multilib g++-multilib \
          libsdl2-dev:i386 libsdl2-mixer-dev:i386 \
          libpng-dev:i386 libpng++-dev:i386 \
          libz-dev:i386 \
          -o APT::Immediate-Configure=0
        
    - name: cmake release
      run: |
        cd ${{ github.workspace }}
        mkdir build_release
        cd build_release
        cmake -DCMAKE_BUILD_TYPE=Release -DCOMPATIBILITY_32_PATH="${{env.COMPATIBILITY_32_PATH}}" ..
        
    - name: make release
      run: |
        cd ${{ github.workspace }}
        cd build_release
        curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -o build-wrapper-linux-x86.zip
        build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output make

    - name: sonarcloud scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
        unzip sonar-scanner-cli-4.4.0.2170-linux.zip
        sonar-scanner-4.4.0.2170-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io