name: MSBuild Logic Test

on: 
  push:
    branches:
      [ master, development ]
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM: [x86, x64]

    steps:
    - name: Archive x86
      if: ${{ matrix.BUILD_CONFIGURATION == 'Release' && matrix.BUILD_PLATFORM == 'x86' }}    
      run: |
        Write-Host "Archive x86"
        Write-Host ${{ GITHUB.HEAD_REF }} 
        Write-Host ${{ GITHUB.REF_NAME }} 
        Write-Host ${{ GITHUB.REF  }} 
        
    - name: Archive x64
      if: ${{ matrix.BUILD_CONFIGURATION == 'Release' && matrix.BUILD_PLATFORM == 'x64' }}
      run: |
        Write-Host "Archive x64"
        Write-Host ${{ github.head_ref }} 
        Write-Host ${{ github.ref_name }} 
        Write-Host ${{ github.ref  }} 