name: MSBuild CI

on: 
  push:
    branches:
      [ master, development ]
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM: [x86, x64]

    steps:
    - name: Archive x86
      if: ${{ env.GITHUB_REF_NAME == 'fix-archive-logic' && matrix.BUILD_CONFIGURATION == 'Release' && matrix.BUILD_PLATFORM == 'x86' }}    
      run: |
        echo "Archive x86"
        echo "${{ env.GITHUB_HEAD_REF }}"
        echo "${{ env.GITHUB_REF_NAME }}"
        echo "${{ env.GITHUB_REF }}"
        
    - name: Archive x64
      if: ${{ env.GITHUB_REF_NAME == 'fix-archive-logic' && matrix.BUILD_CONFIGURATION == 'Release' && matrix.BUILD_PLATFORM == 'x64' }}
      run: |
        echo "Archive x64"
        echo "${{ env.GITHUB_HEAD_REF }}"
        echo "${{ env.GITHUB_REF_NAME }}"
        echo "${{ env.GITHUB_REF }}"